[package]
name = "last_chair"
version = "0.2.0"

[[target.starknet-contract]]
sierra = true

[dependencies]
starknet = ">=2.9.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.15.5" }
